owner: BexlyApp
repo: Status

sites:
  - name: AI Service
    url: https://asia-southeast1-bexly-app.cloudfunctions.net/aiHealthCheck
    method: GET
    expectedStatusCodes:
      - 200

  - name: Telegram Bot
    url: https://asia-southeast1-bexly-app.cloudfunctions.net/telegramWebhook
    method: GET
    expectedStatusCodes:
      - 200
      - 405

  - name: Messenger Bot
    url: https://asia-southeast1-bexly-app.cloudfunctions.net/messengerWebhook
    method: GET
    expectedStatusCodes:
      - 200
      - 403
      - 405

  - name: Firebase
    url: https://bexly-app.firebaseapp.com
    expectedStatusCodes:
      - 200
      - 404

status-website:
  cname: status.bexly.app
  logoUrl: https://raw.githubusercontent.com/BexlyApp/Status/master/assets/logo.png
  name: Bexly Status
  introTitle: "**Bexly** service status"
  introMessage: Real-time monitoring for Bexly services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
